name: Test validation

on: [push, pull_request]

jobs:
  check-constraint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js (except for Windows)
        if: ${{ runner.os != 'Windows' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      # https://github.com/approvals/Approvals.NodeJS/issues/176
      - name: Set up Node.js (for Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        shell: sh
        run: ./test/check-observations.sh

      - name: Show test results
        if: ${{ always() }}
        shell: sh
        run: for file in test/observations/*.log ; do echo === $file === ; cat $file ; done

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-observations
          path: test

  check-cube:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        profile:
          - basic-cube-constraint
          - standalone-constraint-constraint
          - profile-visualize
          - profile-opendataswiss
          - profile-opendataswiss-lindas
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js (except for Windows)
        if: ${{ runner.os != 'Windows' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      # https://github.com/approvals/Approvals.NodeJS/issues/176
      - name: Set up Node.js (for Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        shell: sh
        run: ./test/check-metadata.sh --profile=${{ matrix.profile }}

      - name: Show test results
        if: ${{ always() }}
        shell: sh
        run: for file in test/${{ matrix.profile }}/*.log ; do echo === $file === ; cat $file ; done

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-${{ matrix.profile }}
          path: test
